"""events

Revision ID: 0b82a800daec
Revises: 37e2d33ecbff
Create Date: 2026-09-23 20:16:00.529109

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b82a800daec"
down_revision: Union[str, Sequence[str], None] = "37e2d33ecbff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("organizer_profile_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "concert",
                "conference",
                "sport",
                "theater",
                "other",
                name="eventcategory",
                native_enum=False,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("cover_image_url", sa.String(length=512), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "cancelled",
                "suspended",
                name="eventstatus",
                native_enum=False,
                length=20,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum(
                "public",
                "unlisted",
                "private",
                name="eventvisibility",
                native_enum=False,
                length=20,
            ),
            server_default="public",
            nullable=False,
        ),
        sa.Column(
            "seating_mode",
            sa.Enum(
                "general_admission", "assigned", name="seatingmode", native_enum=False, length=20
            ),
            server_default="general_admission",
            nullable=False,
        ),
        sa.Column("venue_name", sa.String(length=300), nullable=False),
        sa.Column("venue_address", sa.Text(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("registration_opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registration_closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('concert', 'conference', 'sport', 'theater', 'other')",
            name=op.f("ck_events_category"),
        ),
        sa.CheckConstraint(
            "seating_mode IN ('general_admission', 'assigned')", name=op.f("ck_events_seating_mode")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'cancelled', 'suspended')",
            name=op.f("ck_events_status"),
        ),
        sa.CheckConstraint(
            "visibility IN ('public', 'unlisted', 'private')", name=op.f("ck_events_visibility")
        ),
        sa.CheckConstraint(
            "capacity IS NULL OR capacity > 0", name=op.f("ck_events_capacity_positive")
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_events_ends_after_starts")),
        sa.CheckConstraint(
            "registration_opens_at IS NULL OR registration_closes_at IS NULL OR registration_closes_at > registration_opens_at",
            name=op.f("ck_events_registration_window_order"),
        ),
        sa.ForeignKeyConstraint(
            ["organizer_profile_id"],
            ["organizer_profiles.id"],
            name=op.f("fk_events_organizer_profile_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("slug", name=op.f("uq_events_slug")),
    )
    op.create_index(
        op.f("ix_events_organizer_profile_id"), "events", ["organizer_profile_id"], unique=False
    )
    op.create_index(
        "ix_events_status_visibility_starts_at",
        "events",
        ["status", "visibility", "starts_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_status_visibility_starts_at", table_name="events")
    op.drop_index(op.f("ix_events_organizer_profile_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
