"""ticket types and staff

Revision ID: a95da3a018b6
Revises: 0b82a800daec
Create Date: 2026-09-23 21:47:26.239318

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a95da3a018b6"
down_revision: Union[str, Sequence[str], None] = "0b82a800daec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff_assignments",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("event_admin", name="staffrole", native_enum=False, length=20),
            server_default="event_admin",
            nullable=False,
        ),
        sa.Column("assigned_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role in ('event_admin')", name=op.f("ck_staff_assignments_role")),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["users.id"],
            name=op.f("fk_staff_assignments_assigned_by_user_id"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_staff_assignments_event_id")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_staff_assignments_user_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_assignments")),
        sa.UniqueConstraint("event_id", "user_id", name="uq_staff_assignments_event_id_user_id"),
    )
    op.create_index(
        op.f("ix_staff_assignments_user_id"), "staff_assignments", ["user_id"], unique=False
    )
    op.create_table(
        "ticket_types",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("currency", sa.CHAR(length=3), server_default="KZT", nullable=False),
        sa.Column("quantity_total", sa.Integer(), nullable=False),
        sa.Column("quantity_sold", sa.Integer(), server_default="0", nullable=False),
        sa.Column("quantity_reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sales_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sales_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_per_order", sa.Integer(), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_per_order IS NULL OR max_per_order>0",
            name=op.f("ck_ticket_types_max_per_order_positive"),
        ),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_ticket_types_price_non_negative")),
        sa.CheckConstraint(
            "quantity_sold + quantity_reserved <= quantity_total",
            name=op.f("ck_ticket_types_inventory_within_total"),
        ),
        sa.CheckConstraint(
            "quantity_sold >= 0 AND quantity_reserved >= 0",
            name=op.f("ck_ticket_types_counters_non_negative"),
        ),
        sa.CheckConstraint(
            "sales_start_at IS NULL OR sales_end_at IS NULL OR sales_end_at > sales_start_at",
            name=op.f("ck_ticket_types_sales_window_order"),
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], name=op.f("fk_ticket_types_event_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_types")),
    )
    op.create_index(op.f("ix_ticket_types_event_id"), "ticket_types", ["event_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_types_event_id"), table_name="ticket_types")
    op.drop_table("ticket_types")
    op.drop_index(op.f("ix_staff_assignments_user_id"), table_name="staff_assignments")
    op.drop_table("staff_assignments")
    # ### end Alembic commands ###
